#ifndef PEAR_VERSION_H
#define PEAR_VERSION_H

#define PEAR_VERSION_MAJOR 0
#define PEAR_VERSION_MINOR 0
#define PEAR_VERSION_PATCH 0

#define PEAR_STRING_LITERAL(x) #x
#define PEAR_STRING(x)         PEAR_STRING_LITERAL(x)

#define PEAR_VERSION PEAR_STRING(PEAR_VERSION_MAJOR) "." PEAR_STRING(PEAR_VERSION_MINOR) "." PEAR_STRING(PEAR_VERSION_PATCH)

#endif // PEAR_VERSION_H
