#ifndef PEAR_VERSION_H
#define PEAR_VERSION_H

#define PEAR_MAJOR_VERSION 0
#define PEAR_MINOR_VERSION 0
#define PEAR_PATCH_VERSION 0

#define PEAR_STRING_LITERAL(x) #x
#define PEAR_STRING(x)         PEAR_STRING_LITERAL(x)

#define PEAR_VERSION PEAR_STRING(PEAR_MAJOR_VERSION) "." PEAR_STRING(PEAR_MINOR_VERSION) "." PEAR_STRING(PEAR_PATCH_VERSION)

#endif // PEAR_VERSION_H
