name: Integrate
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: holepunchto/actions/node-base@v1
      - run: npm run lint
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            platform: linux
            arch: x64
            flags: --sanitize address
          - os: ubuntu-22.04-arm
            platform: linux
            arch: arm64
          - os: ubuntu-24.04
            platform: android
            arch: x64
            flags: -D ANDROID_STL=c++_static
          - os: ubuntu-24.04
            platform: android
            arch: ia32
            flags: -D ANDROID_STL=c++_static
          - os: ubuntu-24.04
            platform: android
            arch: arm64
            flags: -D ANDROID_STL=c++_static
          - os: ubuntu-24.04
            platform: android
            arch: arm
            flags: -D ANDROID_STL=c++_static
          - os: macos-15-intel
            platform: darwin
            arch: x64
            flags: --sanitize address
          - os: macos-15
            platform: darwin
            arch: arm64
            flags: --sanitize address
          - os: macos-15
            platform: ios
            arch: arm64
          - os: macos-15
            platform: ios
            arch: arm64
            tags: -simulator
            flags: --simulator
          - os: macos-15
            platform: ios
            arch: x64
            tags: -simulator
            flags: --simulator
          - os: windows-2022
            platform: win32
            arch: x64
          - os: windows-11-arm
            platform: win32
            arch: arm64
    runs-on: ${{ matrix.os }}
    name: Test / ${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.tags }}
    steps:
      - uses: holepunchto/actions/node-base@v1
      - uses: holepunchto/actions/setup-llvm@v1
      - uses: holepunchto/actions/setup-nasm@v1
      - uses: holepunchto/actions/compile-prebuilds@v1
        with:
          platform: ${{ matrix.platform }}
          arch: ${{ matrix.arch }}
          flags: ${{ matrix.flags }}
          tags: ${{ matrix.tags}}
      - run: bare-make test
        env:
          LSAN_OPTIONS: suppressions=test/leaks.txt
        if: ${{ matrix.platform == 'linux' || matrix.platform == 'darwin' || matrix.platform == 'win32' }}
